# ROS2 environment
services:
  ros2:
    build: .
    container_name: rigor
    command : tail -f /dev/null
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY
    ports:
      - "3000:3000"
      - "5000:5000"
      - "9876:9876"
      # Forward the ROS port
      # - "7400:7400"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/ros2_jazzy/workspace
