FROM ubuntu:24.04

# Install Bazel

WORKDIR /BAZEL_SETUP

RUN apt update && apt install apt-transport-https curl gnupg -y && \
    curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg && \
    mv bazel-archive-keyring.gpg /usr/share/keyrings && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list && \
    apt update && apt install bazel -y

# Install Bazel Using Bazelisk

RUN apt update && apt install curl git -y

RUN curl -sSL https://github.com/bazelbuild/bazelisk/releases/download/v1.25.0/bazelisk-amd64.deb -o /tmp/bazelisk.deb && \
    apt install /tmp/bazelisk.deb -y

# ------------------ Install ROS ----------------------------------------
ENV DEBIAN_FRONTEND=noninteractive  

RUN locale && \
    apt update && apt install locales && \
    locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

ENV LANG=en_US.UTF-8

RUN apt install software-properties-common -y && add-apt-repository universe

RUN apt update && apt install curl -y

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

# --------- Install the Dev tools ------------

RUN apt update && apt install ros-jazzy-desktop ros-dev-tools -y

# Install pip
RUN apt install python3-pip -y

# --------------------------------------------------------------------------
# RUN useradd -ms /bin/bash COOP && echo "COOP:password" | chpasswd
# RUN echo "COOP ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# USER COOP

# Add COOP to the sudoers

ENV PIP_BREAK_SYSTEM_PACKAGES=1

# add that file to the path
WORKDIR /FORSYTH_WORKSPACE
# COPY . . 