# ROS2 environment
services:
  ros2:
    build: 
      context: .
      dockerfile: Dockerfile.2
    container_name: rigor
    command: tail -f /dev/null
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
      - USER=$USER
      # - HOME=$HOME
    user: "1000:1000"  # Set both user and group IDs to the current user
    network_mode: host
    working_dir: $PWD  # Correct working directory for the user
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $PWD:$PWD  # Mount the working directory correctly inside the container
      # Link the cache for bazel
      - ./bazel-data:/.cache

