# ROS2 environment
services:
  ros2:
    build: .
    container_name: rigor
    command : tail -f /dev/null
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/ros2_jazzy/workspace

  isaac:
    image: nvcr.io/nvidia/isaac-sim:4.2.0
    container_name: isaac
    command: ./runheadless.native.sh -v
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - /var/run/utmp:/var/run/utmp
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
