# - ros_topic_name: "clock"
#   gz_topic_name: "/world/default/clock"
#   ros_type_name: "rosgraph_msgs/msg/Clock"
#   gz_type_name: "gz.msgs.Clock"
#   direction: GZ_TO_ROS  # This maps Gazebo's clock to ROS's clock for time synchronization

- ros_topic_name: "joint_states"
  gz_topic_name: "/model/hermes_robot_description/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS  # This maps the joint states from Gazebo to ROS
